### ISSUE TITLE
RAM and GPU RAM Usage

### ISSUE THREAD

**Issue by stunback** [rhett-chen/graspness_implementation#1]
Hello
I'm interested in your implementation of  the ICCV paper 'Graspness Discovery', and in the graspnet1billion baseline, I notice that the original authors' training process occupies a large volume of RAM about over 128GB. I'm curious about the RAM usage in your training code.

Thank a lot.

**Comment by rhett-chen** [comment]
32G RAM is OK

**Comment by rhett-chen** [comment]
32G RAM is OK, you need to simplify the dataset first.

**Comment by stunback** [comment]
Thanks, it helps a lot!
