### ISSUE TITLE
potential bug

### ISSUE THREAD

**Issue by Fang-Haoshu** [rhett-chen/graspness_implementation#10]
Hi Chen, thanks for your reimplementation. There is a potential bug we identify. During dataset simplification, you limit the maximum grasp point to 4820 on each object. You might also select the corresponding points in the collision label. Otherwise, the collision label for those objects will be wrong.

**Comment by rhett-chen** [comment]
Hi, thanks, it is a bug and I will fix it.  Only the knife object needs to be downsampled, so it has limited impact on the performance.
