### ISSUE TITLE
questions about onnx export

### ISSUE THREAD

**Issue by yongjingli** [rhett-chen/graspness_implementation#12]
Thanks for your nice repo firstly. And I find it looks diffcult to export onnx model for the tensorRT deploy because of MinkowskiEngine. I want to ask if we find a friendly way to build the backbone for onnx export or tensorRT deploy?  @rhett-chen

**Comment by rhett-chen** [comment]
The model is trained on GraspNet-1Billion dataset and it is freely available for non-commercial use.

**Comment by Shuo666-wang** [comment]
? Your answer did not been about this question.
