### ISSUE TITLE
Trained Weights

### ISSUE THREAD

**Issue by qingchenkanlu** [rhett-chen/graspness_implementation#13]
Hello, can I get your trained weights? my email is 768837040@qq.com, thank you!
Also, I want to ask about how many epochs do you train the network? I train the network for 18 epochs, and the AP of Seen is only 55.
The number of points in the training process affects the final performance?

**Comment by rhett-chen** [comment]
Hi, I trained the network for 10 epochs.

**Comment by elenacliu** [comment]
Hi, thanks for your great work, could you share the pretrained weights with me? My email: [elena.cliu@gmail.com](elena.cliu@gmail.com)

Thank you!
Best regards,
Elena
