### ISSUE TITLE
在加载数据集的脚本文件graspnet_dataset.py，可能存在的一个错误。

### ISSUE THREAD

**Issue by yaoyao-sourse** [rhett-chen/graspness_implementation#15]
该文件第38行，self.sceneIds = list(range(101, 130))，，这里的101是不是应该修改为100？在graspnet中，这里的数值也是100。

因为0-99为训练集，100-129是seen，这里我想向您确认一下是否有错，因为这会影响到训练以及测试的结果。

非常感谢您对该论文的复现工作！

**Comment by rhett-chen** [comment]
你好，是的，test seen应该是list(range(100, 130))，这里是我之前自己测试的时候改了的，忘记改回来了。
