### ISSUE TITLE
Pretrain weights.

### ISSUE THREAD

**Issue by wht1712** [rhett-chen/graspness_implementation#16]
Hello Rhett Chen,
Thanks for your great work.
Could you share the pretrained weights to me? 
my email: 1778337314@qq.com
Thank you!

**Comment by wht1712** [comment]
And, why the obj_ids in vis inference always is -1 ? Looking forward to your reply.

**Comment by rhett-chen** [comment]
Hi, in test phase, we don't care the specific object in a scene, the ap is calculated across the whole scene.
