### ISSUE TITLE
进行测试时，AP选择的问题

### ISSUE THREAD

**Issue by baixiaomihu** [rhett-chen/graspness_implementation#18]
你好作者，请问对训练好的权重进行测试时，怎么样设置不同的AP，比如您论文里的AP0.8和AP0.4，以及怎么分别测试Similar 和Novel的AP结果呢？是只需要更改：
test_dataset = GraspNetDataset(cfgs.dataset_root, split='test_seen', camera=cfgs.camera, num_points=cfgs.num_point,  
                               voxel_size=cfgs.voxel_size, remove_outlier=True, augment=False, load_label=False)
ge = GraspNetEval(root=cfgs.dataset_root, camera=cfgs.camera, split='test_seen')
这两个地方吗？

**Comment by rhett-chen** [comment]
修改你所提到的地方可以测试similar和novel的ap。至于如何获取AP0.8、AP0.4等，你需要拿到API返回的Top50抓取的score矩阵，直接对score矩阵求均值即为AP，对score矩阵第二维度不同部分取均值可获取AP0.8等信息，具体需要看一下论文中AP的定义以及API中相应代码。
