### ISSUE TITLE
Need trained weights

### ISSUE THREAD

**Issue by QiuJunning** [rhett-chen/graspness_implementation#2]
Hi, Could you give me your trained weights? If you can,  please send it to my email “junningqiu@163.com”. Thanks!

**Comment by rhett-chen** [comment]
Sorry，I just saw it. The weight has been sent to your email。

**Comment by QiuJunning** [comment]
Thanks！！！

**Comment by patrickeala** [comment]
Hi @rhett-chen, can I also have a copy of the trained weights? My email is patrick.eala@gmail.com thanks a lot!

**Comment by rhett-chen** [comment]
> [patrick.eala@gmail.com](mailto:patrick.eala@gmail.com)

I have sent it to you

**Comment by paolotron** [comment]
Hi @rhett-chen, could you send me the trained weights? My mail is paolo.98.tron@gmail.com

**Comment by rhett-chen** [comment]
> Hi @rhett-chen, could you send me the trained weights? My mail is [paolo.98.tron@gmail.com](mailto:paolo.98.tron@gmail.com)

I have sent it to you

**Comment by 63445538** [comment]
Hi,

Thank you for your sharing. Could you please also share a checkpoint with me via: [caorui0303@gmail.com](mailto:caorui0303@gmail.com)?

Beat regards,
Rui

**Comment by rhett-chen** [comment]
> Hi,
> 
> Thank you for your sharing. Could you please also share a checkpoint with me via: [caorui0303@gmail.com](mailto:caorui0303@gmail.com)?
> 
> Beat regards, Rui

I have sent it to you

**Comment by 63445538** [comment]
> > Hi,
> > Thank you for your sharing. Could you please also share a checkpoint with me via: [caorui0303@gmail.com](mailto:caorui0303@gmail.com)?
> > Beat regards, Rui
> 
> I have sent it to you

Thank you.
Best

**Comment by mo704507064** [comment]
Hi,
Thank you for your sharing. Could you please also share a checkpoint with me: mohangjie@gmail.com

Beat regards, Mo

**Comment by qianpeisheng** [comment]
Hi @rhett-chen ,

Thank you so much for sharing this excellent code base. It is a great inspiration to me. 

Can you also share the trained model weights with me? My email address is: [qian_peisheng@i2r-a.star.edu.sg](qian_peisheng@i2r-a.star.edu.sg).

Thank you!

Best regards,
Peisheng

**Comment by jzhzhang** [comment]
@rhett-chen Thank you for making this amazing project available. I would like to inquire whether it would be possible for you to share the pretrained weights with me at jiazhao.zhang@stu.pku.edu.cn. Your help is greatly appreciated.

Best,
Jiazhao

**Comment by Twilight89** [comment]
@rhett-chen Thank you for the open-source code. 

Can you also share the trained model weights with me? My email address is:  975235061@qq.com

Best wishes!
