### ISSUE TITLE
Need Trained Weights

### ISSUE THREAD

**Issue by wybglw** [rhett-chen/graspness_implementation#22]
Hi @rhett-chen  ,

Thank you so much for sharing this excellent code base and it is a great inspiration to me.

Can you also share the trained weights with me? My email address is: [wangyubo1927@outlook.com](mailto:wangyubo1927@outlook.com)

Thank you!

Best regards,

**Comment by GuoPingPan** [comment]
Hi @rhett-chen ,
I need the pretrained weight too. 
Can you share with me? panguoping02@gmail.com

Thank you very much!
