### ISSUE TITLE
GPU memory problem and request for pretrained weights

### ISSUE THREAD

**Issue by lishiyu005** [rhett-chen/graspness_implementation#24]
Dear author,

I need a pretrained weight. Could you send me to my Email lishiyu005@gmail.com? Thank you very much.

When I try to run the command line:
python generate_graspness.py --dataset_root /data3/graspnet --camera_type kinect
I get GPU out of memory error. And I already simplify the labels before I run this script.

In addition, I have GPU memory problem also during training even after I set batch size to 2. I find GPU memory increase from 10GB in the beginning to more than 20GB. I guess the problem also comes from reading labels. Do you know how to fix this issue? Thanks in advance.

Best regards,
Shiyu Li

**Comment by 1mingW** [comment]
I'm facing the same problem. The GPU memory usage becomes even more when I decrease the batch size. Is this same as yours? And when I train a model with more parameters than this, it does not have such problems. Did you manage to solve it already?

**Comment by rhett-chen** [comment]
In my experiment, the GPU memory usage is about 12GB when batch size is 2.  I'm not  sure what's going on with this problem.
