### ISSUE TITLE
test.py AP比论文中的高不少

### ISSUE THREAD

**Issue by qwertyshen1001** [rhett-chen/graspness_implementation#25]
请问运行test.py的时候--collision_thresh -1 是使用了碰撞检测还是没有碰撞检测CD。我按照您开源的代码运行了10个epoach，得到的AP Seen=0 ，690087 4468655022，AP Similar=0 .6030403 100697231，AP Novel=0. 25724010891913146，每一个值都比论文中的高不少，AP Similar甚至提高了5，请问是哪里的问题。

**Comment by rhett-chen** [comment]
--collision_thresh -1 是不会进行碰撞检测的。您的这个结果确实高了很多，看起来像是加有碰撞检测。
