### ISSUE TITLE
the trained weights

### ISSUE THREAD

**Issue by xiaoxingrunning** [rhett-chen/graspness_implementation#3]
Hello, this is a great work.
I want to run test.sh，and need the trained weights. Can you send it directly to me? My email is 1601572231@qq.com. Thank you very much.

**Comment by rhett-chen** [comment]
already sent it to you. Best wish.

**Comment by 63445538** [comment]
> already sent it to you. Best wish.

Hi,

Thank you for your sharing. Could you please also share a checkpoint with me via: caorui0303@gmail.com?

Beat regards,
Rui

**Comment by Akshatha-Jagadish** [comment]
Hi, 

Could you please share the weights via myacc5620@gmail.com?

**Comment by KJZhuAutomatic** [comment]
@xiaoxingrunning hi, could you please share the weight with me? My qq-email is 984443651@qq.com
