### ISSUE TITLE
Intrinsic Camera

### ISSUE THREAD

**Issue by LeVHoangduc** [rhett-chen/graspness_implementation#32]
I want to check image from camera image.
I use L515 realsense to do it. But I have some question about generate cloud from depth image.

At function create_point_cloud_from_depth_image(depth, camera, organized=True), it has a camera parameter.
Camera is generated by  
`camera = CameraInfo(1280.0, 720.0, intrinsic[0][0], intrinsic[1][1], intrinsic[0][2], intrinsic[1][2], factor_depth)`
So, I can get a width, height, fx,fy,cx,cy of Camera. But I'm confused with factor_depth? I tried to print() depth value from dataset, it's [[1000.]], why is number?
For my case, I get a depth value that means depth scale is 0.0002500000118743628!
I read this document and the scale value is also 1000.0. [link](https://www.open3d.org/docs/0.7.0/python_api/open3d.geometry.create_point_cloud_from_depth_image.html#:~:text=Factory%20function%20to%20create%20a%20pointcloud%20from%20a,%3D%20%28u%20-%20cx%29%20%2A%20z%20%2F%20fx)
So, Could you help me to clarify this number?

**Comment by rhett-chen** [comment]
In the GraspNet-1Billion dataset, the actual depth values are multiplied by 1000 to convert them into integers, which then allows the depth values to be stored as an image. Hence, the factor_depth is 1000. If your get the actual depth values, then you can simply set the factor_depth to 1.

**Comment by LeVHoangduc** [comment]
@rhett-chen Sorry for the late reply. I got it. Thanks a lot for your support
