### ISSUE TITLE
Slow generation for graspness

### ISSUE THREAD

**Issue by Xiong5Heng** [rhett-chen/graspness_implementation#39]
Hi,
I have successfully set up the environment and my system configuration is as follows:

- CPU: Intel i7-14700K
- GPU: NVIDIA RTX 3090
- CUDA: 12.1

When I proceed with the first step (generating point-wise graspness), I notice that the generation speed is quite slow. It takes about 2 seconds to generate a single annotation. However, according to the script `generate_graspness.py`, there are 100 scenes in total, and each scene requires 256 annotations.

I would like to know if this speed is normal. If it is not, what could be the potential reasons for this slow performance?

Thank you for your assistance.

**Comment by Xiong5Heng** [comment]
I have got the answer from the email.

**Comment by biosbeta** [comment]
@Xiong5Heng 
请问是怎么解决的呢
