### ISSUE TITLE
ask for pretrained weights

### ISSUE THREAD

**Issue by khanh0812** [rhett-chen/graspness_implementation#5]
Many thanks for your great work, could you please share me the pretrained weights? My email: khanhdb@hcmute.edu.vn

**Comment by rhett-chen** [comment]
Already sent it to you

**Comment by rhett-chen** [comment]
> Many thanks for your great work, could you please share me the pretrained weights? My email: [khanhdb@hcmute.edu.vn](mailto:khanhdb@hcmute.edu.vn)

Has been sent to you
